// Auto-generated handler registration for CSP-compliant event handling
// This file registers all action handlers for the EventBinding system

// EventBinding is already defined in events.js (loaded before this file)
const handlers = {
        "click_0_EQ_switchAcousticsSubTab__spatial": function(event, element) { EQ.switchAcousticsSubTab('spatial') },
        "click_101_TestLab_abxStart": function(event, element) { TestLab.abxStart() },
        "click_103_TestLab_resetBurnin": function(event, element) { TestLab.resetBurnin() },
        "click_104_PEQDB_Module_closeRenameModal": function(event, element) { PEQDB_Module.closeRenameModal() },
        "click_105_EQ_toggleDeEsser": function(event, element) { EQ.toggleDeEsser() },
        "click_106_App_cycleMobileSection__iem____1": function(event, element) { App.cycleMobileSection('iem', -1) },
        "click_107_EQ_switchCategory__basshead": function(event, element) { EQ.switchCategory('basshead') },
        "click_108_EQ_showSmartImportModal": function(event, element) { EQ.showSmartImportModal() },
        "click_109_FindEngine_cycleRightTab_1": function(event, element) { FindEngine.cycleRightTab(1) },
        "click_10_Mascot_triggerTemporaryExpression__soundstage___3200___TestLab_playSoundstage": function(event, element) { Mascot.triggerTemporaryExpression('soundstage', 3200); TestLab.playSoundstage() },
        "click_110_App_toggleMobileDrawer": function(event, element) { App.toggleMobileDrawer() },
        "click_111_FindEngine_compareSelected": function(event, element) { FindEngine.compareSelected() },
        "click_112_IEM_selectExportGrade__C": function(event, element) { IEM.selectExportGrade('C') },
        "click_113_EQ_switchAcousticsSubTab__crossover": function(event, element) { EQ.switchAcousticsSubTab('crossover') },
        "click_114_EQ_cycleExportFormat_1": function(event, element) { EQ.cycleExportFormat(1) },
        "click_115_IEM_toggleLibraryModal": function(event, element) { IEM.toggleLibraryModal() },
        "click_116_EQ_toggleLoudness": function(event, element) { EQ.toggleLoudness() },
        "click_119_EQ_processSmartImport": function(event, element) { EQ.processSmartImport() },
        "click_11_FindEngine_toggleTuneWithSpecs": function(event, element) { FindEngine.toggleTuneWithSpecs() },
        "click_121_App_switchTab__find____App_toggleMobileDrawer": function(event, element) { App.switchTab('find'); App.toggleMobileDrawer(); },
        "click_122_EQ_closeGenreTargetPicker__game": function(event, element) { EQ.closeGenreTargetPicker('game') },
        "click_124_IEM_selectExportGrade__D": function(event, element) { IEM.selectExportGrade('D') },
        "click_125_PEQDB_Module_setAlignHz__500": function(event, element) { PEQDB_Module.setAlignHz('500') },
        "click_126_FindEngine_scanTasteMatches": function(event, element) { FindEngine.scanTasteMatches() },
        "click_128_EQ_exitTuningLab_true": function(event, element) { EQ.exitTuningLab(true) },
        "click_129_TestLab_cycleLeftTab__1": function(event, element) { TestLab.cycleLeftTab(-1) },
        "click_130_EQ_switchAcousticsSubTab__coupling": function(event, element) { EQ.switchAcousticsSubTab('coupling') },
        "click_131_PEQDB_Module_toggleTargetSculptor": function(event, element) { PEQDB_Module.toggleTargetSculptor() },
        "click_132_EQ_toggleSpectrumOverlay": function(event, element) { EQ.toggleSpectrumOverlay() },
        "click_133_IEM_addCurrentReviewTag": function(event, element) { IEM.addCurrentReviewTag() },
        "click_135_PEQDB_Module_closeSmartRFModal": function(event, element) { PEQDB_Module.closeSmartRFModal() },
        "click_138_App_triggerPriceSlotMachine": function(event, element) { App.triggerPriceSlotMachine() },
        "click_139_EQ_cycleGearSim_1": function(event, element) { EQ.cycleGearSim(1) },
        "click_140_App_switchTab__iem____App_toggleMobileDrawer": function(event, element) { App.switchTab('iem'); App.toggleMobileDrawer(); },
        "click_141_App_cycleMobileSection__find___1": function(event, element) { App.cycleMobileSection('find', 1) },
        "click_142_TestLab_toggleBurnin": function(event, element) { TestLab.toggleBurnin() },
        "click_143_Mascot_triggerTemporaryExpression__sibilance_pain__2500___TestLab_playSibilanceT": function(event, element) { Mascot.triggerTemporaryExpression('sibilance_pain',2500); TestLab.playSibilanceTest() },
        "click_144_IEM_switchSoundCharTab__bass": function(event, element) { IEM.switchSoundCharTab('bass') },
        "click_145_App_tbClick_1": function(event, element) { App.tbClick(1) },
        "click_147_App_switchTab__visualizer____App_toggleMobileDrawer": function(event, element) { App.switchTab('visualizer'); App.toggleMobileDrawer(); },
        "click_149_IEM_cycleListeningVolume": function(event, element) { IEM.cycleListeningVolume() },
        "click_14_PEQDB_Module_setAlignHz__1000": function(event, element) { PEQDB_Module.setAlignHz('1000') },
        "click_150_IEM_saveToLibrary": function(event, element) { IEM.saveToLibrary() },
        "click_151_EQ_toggleReverb": function(event, element) { EQ.toggleReverb() },
        "click_153_PEQDB_Module_setAlignDb_80": function(event, element) { PEQDB_Module.setAlignDb(80) },
        "click_154_EQ_confirmSavePreset": function(event, element) { EQ.confirmSavePreset() },
        "click_155_EQ_toggleAutoGainMatch": function(event, element) { EQ.toggleAutoGainMatch() },
        "click_156_IEM_cycleRightTab__1": function(event, element) { IEM.cycleRightTab(-1) },
        "click_158_TestLab_toggleSpatialPlay_true": function(event, element) { TestLab.toggleSpatialPlay(true) },
        "click_159_TestLab_clearComparisonTracks": function(event, element) { TestLab.clearComparisonTracks() },
        "click_15_EQ_toggleEQ": function(event, element) { EQ.toggleEQ() },
        "click_160_IEM_cycleDacPower__1": function(event, element) { IEM.cycleDacPower(-1) },
        "click_161_PEQDB_Module_cycleTargetDirection_1": function(event, element) { PEQDB_Module.cycleTargetDirection(1) },
        "click_162_App_cycleMobileSection__find____1": function(event, element) { App.cycleMobileSection('find', -1) },
        "click_163_FindEngine_renderUpgradePathway": function(event, element) { FindEngine.renderUpgradePathway() },
        "click_164_TestLab_toggleFullscreen": function(event, element) { TestLab.toggleFullscreen() },
        "click_165_EQ_cycleReverbPreset": function(event, element) { EQ.cycleReverbPreset() },
        "click_166_PEQDB_Module_clearSmartRF": function(event, element) { PEQDB_Module.clearSmartRF() },
        "click_168_IEM_cycleCrossover": function(event, element) { IEM.cycleCrossover() },
        "click_169_EQ_toggleCrossover": function(event, element) { EQ.toggleCrossover() },
        "click_16_TestLab_cycleLeftTab_1": function(event, element) { TestLab.cycleLeftTab(1) },
        "click_170_EQ_cycleFitDepth": function(event, element) { EQ.cycleFitDepth() },
        "click_171_Tone_toneTogglePlay": function(event, element) { Tone.toneTogglePlay() },
        "click_172_document_getElementById__smart_rf_file___click": function(event, element) { document.getElementById('smart-rf-file').click() },
        "click_173_IEM_switchSoundCharTab__package": function(event, element) { IEM.switchSoundCharTab('package') },
        "click_175_IEM_clearImage_event": function(event, element) { IEM.clearImage(event) },
        "click_176_Mascot_triggerTemporaryExpression__treble__3500___TestLab_playSweep_6000__16000_": function(event, element) { Mascot.triggerTemporaryExpression('treble',3500); TestLab.playSweep(6000, 16000, 3) },
        "click_178_PEQDB_Module_cycleTargetDirection__1": function(event, element) { PEQDB_Module.cycleTargetDirection(-1) },
        "click_17_TestLab_nextHearingStep": function(event, element) { TestLab.nextHearingStep() },
        "click_185_TestLab_toggleBassLeakTest__right": function(event, element) { TestLab.toggleBassLeakTest('right') },
        "click_186_EQ_cycleVizEffect": function(event, element) { EQ.cycleVizEffect() },
        "click_187_App_cycleMobileSection__eq___1": function(event, element) { App.cycleMobileSection('eq', 1) },
        "click_188_App_switchTab__testlab____App_toggleMobileDrawer": function(event, element) { App.switchTab('testlab'); App.toggleMobileDrawer(); },
        "click_18_TestLab_toggleABPlay": function(event, element) { TestLab.toggleABPlay() },
        "click_191_IEM_confirmAndTriggerExport": function(event, element) { IEM.confirmAndTriggerExport() },
        "click_192_EQ_switchCategory__custom": function(event, element) { EQ.switchCategory('custom') },
        "click_193_IEM_cycleFormFactor_1": function(event, element) { IEM.cycleFormFactor(1) },
        "click_194_PEQDB_Module_toggleDrawMode": function(event, element) { PEQDB_Module.toggleDrawMode() },
        "click_196_IEM_saveConfig": function(event, element) { IEM.saveConfig() },
        "click_197_EQ_applyGenreTargetAutoEQ__music": function(event, element) { EQ.applyGenreTargetAutoEQ('music') },
        "click_198_App_switchTab__iem": function(event, element) { App.switchTab('iem') },
        "click_19_App_switchTab__eq": function(event, element) { App.switchTab('eq') },
        "click_200_IEM_recenterImage": function(event, element) { IEM.recenterImage() },
        "click_201_IEM_cycleExportThemeDirection_1": function(event, element) { IEM.cycleExportThemeDirection(1) },
        "click_202_PEQDB_Module_cycleAlignDb": function(event, element) { PEQDB_Module.cycleAlignDb() },
        "click_203_PEQDB_Module_executeCurrentCurveTool": function(event, element) { PEQDB_Module.executeCurrentCurveTool() },
        "click_204_EQ_cycleTapeMod_1": function(event, element) { EQ.cycleTapeMod(1) },
        "click_205_TestLab_convertHearingToEQ": function(event, element) { TestLab.convertHearingToEQ() },
        "click_206_EQ_executeCurrentExportFormat": function(event, element) { EQ.executeCurrentExportFormat() },
        "click_207_EQ_saveCurrentAsCustomPreset": function(event, element) { EQ.saveCurrentAsCustomPreset() },
        "click_208_IEM_closeExportModal": function(event, element) { IEM.closeExportModal() },
        "click_209_App_cycleTheme": function(event, element) { App.cycleTheme() },
        "click_20_EQ_prevTrack": function(event, element) { EQ.prevTrack() },
        "click_212_Accessibility_toggleBlueLightFilter": function(event, element) { Accessibility.toggleBlueLightFilter() },
        "click_213_IEM_toggleSensUnit": function(event, element) { IEM.toggleSensUnit() },
        "click_214_document_getElementById__image_upload___click": function(event, element) { document.getElementById('image-upload').click() },
        "click_215_EQ_toggleGapless": function(event, element) { EQ.toggleGapless() },
        "click_216_IEM_cycleLeftTab__1": function(event, element) { IEM.cycleLeftTab(-1) },
        "click_217_IEM_compareSelected": function(event, element) { IEM.compareSelected() },
        "click_218_EQ_toggleShuffle": function(event, element) { EQ.toggleShuffle() },
        "click_219_TestLab_playChannelTone__right": function(event, element) { TestLab.playChannelTone('right') },
        "click_21_EQ_toggleGenreTargetList__game": function(event, element) { EQ.toggleGenreTargetList('game') },
        "click_220_EQ_togglePreventClipping": function(event, element) { EQ.togglePreventClipping() },
        "click_221_Mascot_triggerTemporaryExpression__focus___3200___TestLab_playDetailRetrieval": function(event, element) { Mascot.triggerTemporaryExpression('focus', 3200); TestLab.playDetailRetrieval() },
        "click_223_IEM_cycleFormFactor__1": function(event, element) { IEM.cycleFormFactor(-1) },
        "click_224_IEM_cycleConnector_1": function(event, element) { IEM.cycleConnector(1) },
        "click_225_PEQDB_Module_pasteSmartRF": function(event, element) { PEQDB_Module.pasteSmartRF() },
        "click_226_FindEngine_cycleGoalIndex_1": function(event, element) { FindEngine.cycleGoalIndex(1) },
        "click_227_FindEngine_scanGiantKillers": function(event, element) { FindEngine.scanGiantKillers() },
        "click_228_EQ_closeSavePresetModal": function(event, element) { EQ.closeSavePresetModal() },
        "click_229_EQ_toggleTempo": function(event, element) { EQ.toggleTempo() },
        "click_22_IEM_cycleWay": function(event, element) { IEM.cycleWay() },
        "click_230_TestLab_cycleRightTab_1": function(event, element) { TestLab.cycleRightTab(1) },
        "click_231_EQ_closeGenreTargetPicker__music": function(event, element) { EQ.closeGenreTargetPicker('music') },
        "click_233_IEM_showExportModal": function(event, element) { IEM.showExportModal() },
        "click_234_IEM_switchSoundCharTab__stage": function(event, element) { IEM.switchSoundCharTab('stage') },
        "click_235_EQ_cycleTipSound": function(event, element) { EQ.cycleTipSound() },
        "click_236_TestLab_abxChoose__A": function(event, element) { TestLab.abxChoose('A') },
        "click_237_EQ_toggleActiveGraphFullscreen": function(event, element) { EQ.toggleActiveGraphFullscreen() },
        "click_238_document_getElementById__review_notes___value_____IEM_updateAll____showToast__No": function(event, element) { document.getElementById('review-notes').value=''; IEM.updateAll(); showToast('Notes cleared.', '🗑️'); },
        "click_239_PEQDB_Module_cycleResolutionDirection__1": function(event, element) { PEQDB_Module.cycleResolutionDirection(-1) },
        "click_23_EQ_cycleCrossoverType__1": function(event, element) { EQ.cycleCrossoverType(-1) },
        "click_241_IEM_switchSoundCharTab__treble": function(event, element) { IEM.switchSoundCharTab('treble') },
        "click_242_TestLab_stopChannelTone": function(event, element) { TestLab.stopChannelTone() },
        "click_243_IEM_cycleReviewTag_1": function(event, element) { IEM.cycleReviewTag(1) },
        "click_244_EQ_toggleGenreTargetList__music": function(event, element) { EQ.toggleGenreTargetList('music') },
        "click_246_IEM_cycleReviewTag__1": function(event, element) { IEM.cycleReviewTag(-1) },
        "click_247_TestLab_abxCycleTrials__1": function(event, element) { TestLab.abxCycleTrials(-1) },
        "click_248_PEQDB_Module_cycleResolutionDirection_1": function(event, element) { PEQDB_Module.cycleResolutionDirection(1) },
        "click_249_EQ_cycleExportFormat__1": function(event, element) { EQ.cycleExportFormat(-1) },
        "click_24_FindEngine_cycleBaseline": function(event, element) { FindEngine.cycleBaseline() },
        "click_250_EQ_calibrateLoudnessFromVolume": function(event, element) { EQ.calibrateLoudnessFromVolume() },
        "click_251_IEM_cycleDacPower_1": function(event, element) { IEM.cycleDacPower(1) },
        "click_252_TestLab_stopBassLeakTest": function(event, element) { TestLab.stopBassLeakTest() },
        "click_253_IEM_cycleExportThemeDirection__1": function(event, element) { IEM.cycleExportThemeDirection(-1) },
        "click_255_App_cycleMobileSection__testlab___1": function(event, element) { App.cycleMobileSection('testlab', 1) },
        "click_256_FindEngine_cycleRightTab__1": function(event, element) { FindEngine.cycleRightTab(-1) },
        "click_257_App_switchTab__eq____App_toggleMobileDrawer": function(event, element) { App.switchTab('eq'); App.toggleMobileDrawer(); },
        "click_258_EQ_cycleCrossoverType_1": function(event, element) { EQ.cycleCrossoverType(1) },
        "click_259_PEQDB_Module_confirmRename": function(event, element) { PEQDB_Module.confirmRename() },
        "click_25_Mascot_triggerTemporaryExpression__sub_bass__2500___TestLab_playSweep_20__60__2": function(event, element) { Mascot.triggerTemporaryExpression('sub_bass',2500); TestLab.playSweep(20, 60, 2) },
        "click_260_EQ_cycleGearSim__1": function(event, element) { EQ.cycleGearSim(-1) },
        "click_261_App_cycleMobileSection__testlab____1": function(event, element) { App.cycleMobileSection('testlab', -1) },
        "click_263_EQ_toggleRepeat": function(event, element) { EQ.toggleRepeat() },
        "click_264_Mascot_triggerTemporaryExpression__polarity___3200___TestLab_playPolarityTest": function(event, element) { Mascot.triggerTemporaryExpression('polarity', 3200); TestLab.playPolarityTest() },
        "click_265_EQ_enablePreampEdit": function(event, element) { EQ.enablePreampEdit() },
        "click_266_TestLab_playChannelTone__left": function(event, element) { TestLab.playChannelTone('left') },
        "click_267_App_toggleMobileSidebar": function(event, element) { App.toggleMobileSidebar() },
        "click_269_TestLab_lockResonancePeak": function(event, element) { TestLab.lockResonancePeak() },
        "click_26_App_switchTab__settings____App_toggleMobileDrawer": function(event, element) { App.switchTab('settings'); App.toggleMobileDrawer(); },
        "click_272_EQ_toggleCompressor": function(event, element) { EQ.toggleCompressor() },
        "click_273_TestLab_cycleBurninSignal": function(event, element) { TestLab.cycleBurninSignal() },
        "click_274_FindEngine_scanAndMatch": function(event, element) { FindEngine.scanAndMatch() },
        "click_275_EQ_exitTuningLab_false": function(event, element) { EQ.exitTuningLab(false) },
        "click_277_Tone_toneSweep": function(event, element) { Tone.toneSweep() },
        "click_27_TestLab_toggleBassLeakTest__left": function(event, element) { TestLab.toggleBassLeakTest('left') },
        "click_280_IEM_selectExportGrade__A": function(event, element) { IEM.selectExportGrade('A') },
        "click_281_TestLab_playChannelTone__center": function(event, element) { TestLab.playChannelTone('center') },
        "click_282_EQ_clearPlaylist": function(event, element) { EQ.clearPlaylist() },
        "click_283_PEQDB_Module_clearState": function(event, element) { PEQDB_Module.clearState() },
        "click_284_IEM_switchSoundCharTab__fit": function(event, element) { IEM.switchSoundCharTab('fit') },
        "click_285_PEQDB_Module_generateLeastSquaresAutoEQ": function(event, element) { PEQDB_Module.generateLeastSquaresAutoEQ() },
        "click_287_App_triggerMushroomEgg_this": function(event, element) { App.triggerMushroomEgg(this) },
        "click_288_EQ_switchFaderTab__standard": function(event, element) { EQ.switchFaderTab('standard') },
        "click_28_TestLab_cycleBurninTime": function(event, element) { TestLab.cycleBurninTime() },
        "click_291_App_switchTab__visualizer": function(event, element) { App.switchTab('visualizer') },
        "click_292_IEM_selectExportGrade__F": function(event, element) { IEM.selectExportGrade('F') },
        "click_294_EQ_switchCategory__gaming": function(event, element) { EQ.switchCategory('gaming') },
        "click_295_TestLab_abxChoose__B": function(event, element) { TestLab.abxChoose('B') },
        "click_298_TestLab_resetHearingTest": function(event, element) { TestLab.resetHearingTest() },
        "click_299_EQ_toggleVisualizerFullscreen": function(event, element) { EQ.toggleVisualizerFullscreen() },
        "click_29_event_stopPropagation": function(event, element) { event.stopPropagation() },
        "click_2_PEQDB_Module_cycleCurveToolIndex__1": function(event, element) { PEQDB_Module.cycleCurveToolIndex(-1) },
        "click_300_PEQDB_Module_setSearchMode__similar": function(event, element) { PEQDB_Module.setSearchMode('similar') },
        "click_302_IEM_selectExportGrade__B": function(event, element) { IEM.selectExportGrade('B') },
        "click_304_App_tbClick_2": function(event, element) { App.tbClick(2) },
        "click_305_EQ_toggleMute": function(event, element) { EQ.toggleMute() },
        "click_306_EQ_togglePlayState": function(event, element) { EQ.togglePlayState() },
        "click_307_TestLab_resetResonance": function(event, element) { TestLab.resetResonance() },
        "click_308_IEM_cycleExportFontDirection_1": function(event, element) { IEM.cycleExportFontDirection(1) },
        "click_30_Mascot_triggerTemporaryExpression__footsteps___3200___TestLab_playFPSImaging": function(event, element) { Mascot.triggerTemporaryExpression('footsteps', 3200); TestLab.playFPSImaging() },
        "click_32_PEQDB_Module_setAlignHz__mean": function(event, element) { PEQDB_Module.setAlignHz('mean') },
        "click_33_Mascot_triggerTemporaryExpression__impact__600___TestLab_playTransientSlam": function(event, element) { Mascot.triggerTemporaryExpression('impact',600); TestLab.playTransientSlam() },
        "click_34_EQ_switchCategory__media": function(event, element) { EQ.switchCategory('media') },
        "click_35_TestLab_startResonanceScan": function(event, element) { TestLab.startResonanceScan() },
        "click_36_EQ_switchCategory__music": function(event, element) { EQ.switchCategory('music') },
        "click_37_FindEngine_cycleFindMode_1": function(event, element) { FindEngine.cycleFindMode(1) },
        "click_38_PEQDB_Module_cycleCurveToolIndex_1": function(event, element) { PEQDB_Module.cycleCurveToolIndex(1) },
        "click_3_IEM_selectExportGrade__S": function(event, element) { IEM.selectExportGrade('S') },
        "click_40_App_switchTab__testlab": function(event, element) { App.switchTab('testlab') },
        "click_42_App_switchTab__find": function(event, element) { App.switchTab('find') },
        "click_43_App_cycleFont": function(event, element) { App.cycleFont() },
        "click_45_PEQDB_Module_setAlignDb_85": function(event, element) { PEQDB_Module.setAlignDb(85) },
        "click_46_EQ_applyGenreTargetAutoEQ__game": function(event, element) { EQ.applyGenreTargetAutoEQ('game') },
        "click_47_EQ_cycleConsoleTab__1": function(event, element) { EQ.cycleConsoleTab(-1) },
        "click_48_TestLab_abxCycleTrials_1": function(event, element) { TestLab.abxCycleTrials(1) },
        "click_49_IEM_resetAll": function(event, element) { IEM.resetAll() },
        "click_4_EQ_cycleTapeMod__1": function(event, element) { EQ.cycleTapeMod(-1) },
        "click_50_toggleAudioMode": function(event, element) { toggleAudioMode() },
        "click_53_PEQDB_Module_cycleAlignHz": function(event, element) { PEQDB_Module.cycleAlignHz() },
        "click_55_FindEngine_scanEndgameSets": function(event, element) { FindEngine.scanEndgameSets() },
        "click_56_FindEngine_cycleFindMode__1": function(event, element) { FindEngine.cycleFindMode(-1) },
        "click_57_Mascot_triggerTemporaryExpression__mid_bass__2200___TestLab_playSweep_60__200__2": function(event, element) { Mascot.triggerTemporaryExpression('mid_bass',2200); TestLab.playSweep(60, 200, 2) },
        "click_59_App_cycleMobileSection__iem___1": function(event, element) { App.cycleMobileSection('iem', 1) },
        "click_60_PEQDB_Module_setAlignDb_75": function(event, element) { PEQDB_Module.setAlignDb(75) },
        "click_61_PEQDB_Module_setAlignDb_0": function(event, element) { PEQDB_Module.setAlignDb(0) },
        "click_62_PEQDB_Module_confirmSmartRF": function(event, element) { PEQDB_Module.confirmSmartRF() },
        "click_63_EQ_toggleGenreTargetPicker__game": function(event, element) { EQ.toggleGenreTargetPicker('game') },
        "click_64_TestLab_Module_cycleSpatialWidth": function(event, element) { TestLab_Module.cycleSpatialWidth() },
        "click_65_IEM_cycleRightTab_1": function(event, element) { IEM.cycleRightTab(1) },
        "click_66_TestLab_toggleSpatialPlay_false": function(event, element) { TestLab.toggleSpatialPlay(false) },
        "click_68_EQ_switchAcousticsSubTab__effects": function(event, element) { EQ.switchAcousticsSubTab('effects') },
        "click_6_IEM_cycleConnector__1": function(event, element) { IEM.cycleConnector(-1) },
        "click_70_EQ_switchFaderTab__advanced": function(event, element) { EQ.switchFaderTab('advanced') },
        "click_72_EQ_cycleSealQuality": function(event, element) { EQ.cycleSealQuality() },
        "click_73_FindEngine_resetFindResults": function(event, element) { FindEngine.resetFindResults() },
        "click_74_TestLab_cycleSpatialSource": function(event, element) { TestLab.cycleSpatialSource() },
        "click_75_EQ_toggleCrossfade": function(event, element) { EQ.toggleCrossfade() },
        "click_76_FindEngine_cycleGoalIndex__1": function(event, element) { FindEngine.cycleGoalIndex(-1) },
        "click_77_EQ_toggleGenreTargetPicker__music": function(event, element) { EQ.toggleGenreTargetPicker('music') },
        "click_78_IEM_cycleExportFontDirection__1": function(event, element) { IEM.cycleExportFontDirection(-1) },
        "click_79_PEQDB_Module_setSearchMode__database": function(event, element) { PEQDB_Module.setSearchMode('database') },
        "click_80_App_switchTab__settings": function(event, element) { App.switchTab('settings') },
        "click_81_EQ_nextTrack": function(event, element) { EQ.nextTrack() },
        "click_82_TestLab_cycleSpatialReverb": function(event, element) { TestLab.cycleSpatialReverb() },
        "click_83_App_cycleMobileSection__eq____1": function(event, element) { App.cycleMobileSection('eq', -1) },
        "click_85_IEM_closeCompare": function(event, element) { IEM.closeCompare() },
        "click_86_PEQDB_Module_setAlignHz__2000": function(event, element) { PEQDB_Module.setAlignHz('2000') },
        "click_87_App_tbClick_3": function(event, element) { App.tbClick(3) },
        "click_88_IEM_cycleLeftTab_1": function(event, element) { IEM.cycleLeftTab(1) },
        "click_89_document_getElementById__spatial_file_input___click": function(event, element) { document.getElementById('spatial-file-input').click() },
        "click_8_document_getElementById__import_input___click": function(event, element) { document.getElementById('import-input').click() },
        "click_90_TestLab_playImaging": function(event, element) { TestLab.playImaging() },
        "click_93_TestLab_toggleChannelSwap": function(event, element) { TestLab.toggleChannelSwap() },
        "click_94_TestLab_cycleRightTab__1": function(event, element) { TestLab.cycleRightTab(-1) },
        "click_95_EQ_cycleConsoleTab_1": function(event, element) { EQ.cycleConsoleTab(1) },
        "click_97_IEM_switchSoundCharTab__mids": function(event, element) { IEM.switchSoundCharTab('mids') },
        "click_98_EQ_closeSmartImportModal": function(event, element) { EQ.closeSmartImportModal() },
        "click_99_EQ_switchCategory__audiophile": function(event, element) { EQ.switchCategory('audiophile') },
        "input_100_TestLab_updateHearingTestVolume": function(event, element) { TestLab.updateHearingTestVolume() },
        "input_117_EQ_updateCrossoverParam__trimHighMid___this_value": function(event, element) { EQ.updateCrossoverParam('trimHighMid', this.value) },
        "input_118_EQ_updateReverbParam__predelaymix___this_value___100": function(event, element) { EQ.updateReverbParam('predelaymix', this.value / 100) },
        "input_120_EQ_updateCompressorParam__release___this_value": function(event, element) { EQ.updateCompressorParam('release', this.value) },
        "input_123_EQ_updateCrossoverParam__freq4___this_value": function(event, element) { EQ.updateCrossoverParam('freq4', this.value) },
        "input_12_PEQDB_Module_handleSmartRFInput": function(event, element) { PEQDB_Module.handleSmartRFInput() },
        "input_134_EQ_updateCrossoverParam__freq2___this_value": function(event, element) { EQ.updateCrossoverParam('freq2', this.value) },
        "input_136_EQ_updateCompressorParam__ratio___this_value___10": function(event, element) { EQ.updateCompressorParam('ratio', this.value / 10) },
        "input_137_IEM_debouncedUpdateAll": function(event, element) { IEM.debouncedUpdateAll() },
        "input_13_EQ_updateLoudnessParam__calibration___this_value": function(event, element) { EQ.updateLoudnessParam('calibration', this.value) },
        "input_146_EQ_updateCrossoverParam__freq3___this_value": function(event, element) { EQ.updateCrossoverParam('freq3', this.value) },
        "input_148_TestLab_updateBurninVolume_this_value": function(event, element) { TestLab.updateBurninVolume(this.value) },
        "input_152_FindEngine_updateEndgameBudgetDisplay_this_value": function(event, element) { FindEngine.updateEndgameBudgetDisplay(this.value) },
        "input_157_FindEngine_handleGkSearchDebounced_this_value": function(event, element) { FindEngine.handleGkSearchDebounced(this.value) },
        "input_174_IEM_onDbSearchInput_this_value": function(event, element) { IEM.onDbSearchInput(this.value) },
        "input_177_EQ_updateCrossfeedLevel_this_value": function(event, element) { EQ.updateCrossfeedLevel(this.value) },
        "input_179_EQ_updateCompressorParam__gain___this_value___10": function(event, element) { EQ.updateCompressorParam('gain', this.value / 10) },
        "input_180_EQ_updateStereoExpand_this_value": function(event, element) { EQ.updateStereoExpand(this.value) },
        "input_181_EQ_updateReverbParam__fade___this_value___100": function(event, element) { EQ.updateReverbParam('fade', this.value / 100) },
        "input_183_EQ_updateCompressorParam__attack___this_value": function(event, element) { EQ.updateCompressorParam('attack', this.value) },
        "input_184_FindEngine_syncDualRange__price": function(event, element) { FindEngine.syncDualRange('price') },
        "input_190_EQ_updateTempoSpeed_this_value": function(event, element) { EQ.updateTempoSpeed(this.value) },
        "input_195_FindEngine_handleUpgradeSearchDebounced_this_value": function(event, element) { FindEngine.handleUpgradeSearchDebounced(this.value) },
        "input_199_IEM_updateBrandSuggestions_this_value": function(event, element) { IEM.updateBrandSuggestions(this.value) },
        "input_1_Tone_updateToneFreq": function(event, element) { Tone.updateToneFreq() },
        "input_222_IEM_debouncedRenderLibrary": function(event, element) { IEM.debouncedRenderLibrary() },
        "input_232_EQ_updateCrossoverParam__trimLowMid___this_value": function(event, element) { EQ.updateCrossoverParam('trimLowMid', this.value) },
        "input_240_EQ_updateMasterTone__treble___this_value": function(event, element) { EQ.updateMasterTone('treble', this.value) },
        "input_245_FindEngine_syncDualRange__year": function(event, element) { FindEngine.syncDualRange('year') },
        "input_254_EQ_updateCompressorParam__threshold___this_value___10": function(event, element) { EQ.updateCompressorParam('threshold', this.value / 10) },
        "input_262_EQ_updateCrossoverParam__trimMid___this_value": function(event, element) { EQ.updateCrossoverParam('trimMid', this.value) },
        "input_270_EQ_updateLoudnessParam__strength___this_value": function(event, element) { EQ.updateLoudnessParam('strength', this.value) },
        "input_271_EQ_updateReverbParam__size___this_value___100": function(event, element) { EQ.updateReverbParam('size', this.value / 100) },
        "input_278_EQ_updateMasterTone__bass___this_value": function(event, element) { EQ.updateMasterTone('bass', this.value) },
        "input_286_Accessibility_handleBalanceInput_this": function(event, element) { Accessibility.handleBalanceInput(this) },
        "input_289_EQ_updateReverbParam__filter___this_value___100": function(event, element) { EQ.updateReverbParam('filter', this.value / 100) },
        "input_290_EQ_updateCrossoverParam__trimLow___this_value": function(event, element) { EQ.updateCrossoverParam('trimLow', this.value) },
        "input_293_EQ_updateDeEsserSens_this_value": function(event, element) { EQ.updateDeEsserSens(this.value) },
        "input_296_IEM_handleGaugeSlider__sensitivity___this_value": function(event, element) { IEM.handleGaugeSlider('sensitivity', this.value) },
        "input_297_IEM_handleZoomSlider_this_value": function(event, element) { IEM.handleZoomSlider(this.value) },
        "input_301_EQ_updateCrossoverParam__trimHigh___this_value": function(event, element) { EQ.updateCrossoverParam('trimHigh', this.value) },
        "input_303_FindEngine_syncUgDualRange__price": function(event, element) { FindEngine.syncUgDualRange('price') },
        "input_31_EQ_setCrossfadeSeconds_this_value": function(event, element) { EQ.setCrossfadeSeconds(this.value) },
        "input_39_EQ_updateMusicVolume_this_value": function(event, element) { EQ.updateMusicVolume(this.value) },
        "input_41_TestLab_updateABFade": function(event, element) { TestLab.updateABFade() },
        "input_44_this_value___this_value_replace____0_9__g": function(event, element) { this.value = this.value.replace(/[^0-9]/g, '') },
        "input_51_IEM_handleGaugeSlider__impedance___this_value": function(event, element) { IEM.handleGaugeSlider('impedance', this.value) },
        "input_52_EQ_updateReverbParam__predelay___this_value___1000": function(event, element) { EQ.updateReverbParam('predelay', this.value / 1000) },
        "input_54_FindEngine_syncUgDualRange__year": function(event, element) { FindEngine.syncUgDualRange('year') },
        "input_5_FindEngine_updateGkBudgetDisplay_this_value": function(event, element) { FindEngine.updateGkBudgetDisplay(this.value) },
        "input_67_EQ_updateCompressorParam__frequency___this_value": function(event, element) { EQ.updateCompressorParam('frequency', this.value) },
        "input_71_EQ_updateReverbParam__damp___this_value___100": function(event, element) { EQ.updateReverbParam('damp', this.value / 100) },
        "input_7_EQ_updateSimulation": function(event, element) { EQ.updateSimulation() },
        "input_84_App_setReadingSize_this_value": function(event, element) { App.setReadingSize(this.value) },
        "input_91_FindEngine_handleTasteSearchDebounced_this_value": function(event, element) { FindEngine.handleTasteSearchDebounced(this.value) },
        "input_92_EQ_updateCrossoverParam__freq1___this_value": function(event, element) { EQ.updateCrossoverParam('freq1', this.value) },
        "input_96_EQ_updatePreamp": function(event, element) { EQ.updatePreamp() },
        "input_9_EQ_updateReverbParam__mix___this_value___100": function(event, element) { EQ.updateReverbParam('mix', this.value / 100) },
        "change_102_TestLab_handleSpatialFile_event": function(event, element) { TestLab.handleSpatialFile(event) },
        "change_167_PEQDB_Module_setTarget_this_value": function(event, element) { PEQDB_Module.setTarget(this.value) },
        "change_182_PEQDB_Module_handleSmartRFFile_event": function(event, element) { PEQDB_Module.handleSmartRFFile(event) },
        "change_210_IEM_toggleBgRemoval_this_checked___this_parentElement_classList_toggle__is_on___": function(event, element) { IEM.toggleBgRemoval(this.checked); this.parentElement.classList.toggle('is-on', this.checked); },
        "change_211_EQ_handleAudioFileSelection_this_files___this_value": function(event, element) { EQ.handleAudioFileSelection(this.files); this.value=''; },
        "change_276_IEM_handleImageUpload_event": function(event, element) { IEM.handleImageUpload(event) },
        "change_279_EQ_handleSmartFileSelect_event": function(event, element) { EQ.handleSmartFileSelect(event) },
        "change_58_FindEngine_rerunGiantKillersIfLive": function(event, element) { FindEngine.rerunGiantKillersIfLive() },
        "change_69_IEM_importConfig_event": function(event, element) { IEM.importConfig(event) },
        "blur_127_EQ_commitPreampEdit": function(event, element) { EQ.commitPreampEdit() },
        "blur_268_setTimeout_______document_getElementById__brand_suggestions___classList_add__hid": function(event, element) { setTimeout(() => document.getElementById('brand-suggestions').classList.add('hidden'), 200) },
        "keydown_189_if_event_key____Enter___EQ_commitPreampEdit": function(event, element) { if(event.key==='Enter') EQ.commitPreampEdit() },
    };

    // Register all handlers
    Object.keys(handlers).forEach(function(action) {
        EventBinding.register(action, handlers[action]);
    });
    console.log('[HandlerRegistry] Registered ' + Object.keys(handlers).length + ' handlers');